"""Dedicated Brief screen for the cos TUI.

Implements an in-app version of the /brief skill from toolbox/brief.md.
- Reads operational data via the shared loader (finances, kb, learning, schedule, knowledge_work/status).
- Performs live READ-ONLY vault scans for inbox, workbench, and journal open questions
  (exactly as described in the skill prompt and PRD-overview-brief.md).
- Displays in the canonical "Overview Brief" format used by briefs/brief-*.md.
- Supports refresh (live re-scan) and write (status.json + brief-YYYY-MM-DD.md).

Grok X-Brief integration (full):
- "Run Grok X-Brief" action (hotkey 'g' + toolbar button) runs real X research synthesis
  (Textual TUI, personal/agentic OS, Grok Build, agent memory/LLM tooling topics via
  x_semantic_search + x_keyword_search) + writes structured threads (title, summary, url,
  relevance to cos, date) via the canonical write_grok_ai_news.
- Writes to the reserved data layer: overview-brief/data/ai-news.json
  (as referenced in overview-brief/inputs/config.json, status.json, build_brief_markdown, PRDs).
- UI surfaces real data in AI News section: count, titles + relevance, "generated by Grok" note.
- Shows step-by-step progress via notifications + auto-refreshes the view.
- All writes strictly to data/ only; honors hard rules (no vault, no inputs/).

Hard rules honored:
- Vault is READ-ONLY. No writes ever touch ~/llm-knowledge-base/.
- Never writes inputs/.
- Timezone always sourced from tasks-calendar/inputs/config.json (ICT).
- Degrades gracefully when vault or data contracts are unavailable.

This is the first Doom-Emacs-style dedicated full-screen view (MVP).
Other views (Research, Capture, Tasks) will follow the same pattern.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from zoneinfo import ZoneInfo

from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Horizontal, VerticalScroll
from textual.reactive import reactive
from textual.screen import Screen
from textual.widgets import Button, Footer, Header, Static

# Reuse the excellent existing data loader (no duplication of load contracts)
from ..data.loader import (
    DEFAULT_COS_ROOT,
    load_all,
    load_knowledge_base,
    load_learning,
    load_runway,
    load_schedule,
    write_grok_ai_news,
)


# --- tiny internal helpers (duplicated  _load_json only; surgical, no loader.py edit) ---

def _load_json(path: Path, default: dict[str, Any] | None = None) -> dict[str, Any]:
    """Load JSON with graceful fallback. Matches loader.py style."""
    if default is None:
        default = {}
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        pass
    return default


def _expand_path(p: str | Path) -> Path:
    return Path(p).expanduser()


def _get_tz() -> ZoneInfo:
    """Never hardcode timezone. Always read from the canonical config."""
    cfg_path = DEFAULT_COS_ROOT / "tasks-calendar" / "inputs" / "config.json"
    cfg = _load_json(cfg_path, {"timezone": "Asia/Ho_Chi_Minh"})
    tz_name = cfg.get("timezone", "Asia/Ho_Chi_Minh")
    try:
        return ZoneInfo(tz_name)
    except Exception:
        return ZoneInfo("Asia/Ho_Chi_Minh")


def _load_vault_config(cos_root: Path = DEFAULT_COS_ROOT) -> dict[str, Any]:
    """Load inbox/workbench paths etc from the overview-brief config (per PRD)."""
    path = cos_root / "overview-brief" / "inputs" / "config.json"
    default = {
        "vault_path": "~/llm-knowledge-base",
        "inbox_path": "~/llm-knowledge-base/raw/inbox",
        "workbench_path": "~/llm-knowledge-base/workbench",
        "open_questions_source": "~/cos/knowledge-base/data/open-questions.json",
        "max_journal_questions": 3,
        "ai_news_path": "~/cos/overview-brief/data/ai-news.json",
    }
    return _load_json(path, default)


def _parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal YAML-ish frontmatter extractor for inbox clippings (title/source/created)."""
    fm: dict[str, str] = {}
    if not text.lstrip().startswith("---"):
        return fm
    try:
        start = text.find("---")
        end = text.find("---", start + 3)
        if end == -1:
            return fm
        block = text[start + 3 : end].strip()
        for line in block.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            k, v = [part.strip() for part in line.split(":", 1)]
            k = k.lower()
            v = v.strip().strip('"').strip("'")
            fm[k] = v
    except Exception:
        pass
    return fm


# --- vault scan logic (directly mirrors toolbox/brief.md Step 2 + PRD spec) ---

def scan_inbox(config: dict[str, Any]) -> dict[str, Any]:
    """Live scan of raw/inbox/ (read-only). Returns count + items with title/source/created/filename."""
    inbox_dir = _expand_path(config.get("inbox_path", "~/llm-knowledge-base/raw/inbox"))
    if not inbox_dir.exists() or not inbox_dir.is_dir():
        return {"count": 0, "items": [], "error": f"Inbox directory not found: {inbox_dir}"}

    items: list[dict[str, Any]] = []
    try:
        md_files = sorted(inbox_dir.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
        for f in md_files:
            try:
                text = f.read_text(encoding="utf-8", errors="replace")
                fm = _parse_frontmatter(text)
                item = {
                    "title": fm.get("title", f.stem),
                    "source": fm.get("source", fm.get("author", "")),
                    "created": fm.get("created", ""),
                    "filename": f.name,
                }
                items.append(item)
            except Exception as e:
                items.append({
                    "title": f.name,
                    "source": "",
                    "created": "",
                    "filename": f.name,
                    "error": str(e),
                })
    except Exception as e:
        return {"count": 0, "items": [], "error": str(e)}
    return {"count": len(items), "items": items}


def scan_workbench(config: dict[str, Any]) -> dict[str, Any]:
    """Live scan of workbench/ (read-only). Age from mtime (no frontmatter assumed, per spec)."""
    wb_dir = _expand_path(config.get("workbench_path", "~/llm-knowledge-base/workbench"))
    if not wb_dir.exists() or not wb_dir.is_dir():
        return {"count": 0, "items": [], "error": f"Workbench directory not found: {wb_dir}"}

    now = datetime.now()
    items: list[dict[str, Any]] = []
    try:
        for f in wb_dir.glob("*.md"):
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime)
                days_old = (now - mtime).days
                items.append({"filename": f.name, "days_old": days_old})
            except Exception:
                items.append({"filename": f.name, "days_old": 999, "error": "stat failed"})
    except Exception as e:
        return {"count": 0, "items": [], "error": str(e)}

    items.sort(key=lambda x: x.get("days_old", 999))
    return {"count": len(items), "items": items}


def get_journal_questions(cos_root: Path = DEFAULT_COS_ROOT, max_n: int | None = None) -> dict[str, Any]:
    """Filter open-questions.json for journal entries (source/path contains /journal/).
    Takes most recent N (default from config or 3).
    """
    cfg = _load_vault_config(cos_root)
    max_n = max_n or int(cfg.get("max_journal_questions", 3))
    oq_path = cos_root / "knowledge-base" / "data" / "open-questions.json"
    data = _load_json(oq_path, {"open": [], "count": 0})
    open_list = data.get("open", []) or []
    if not isinstance(open_list, list):
        open_list = []

    journal = []
    for entry in open_list:
        if not isinstance(entry, dict):
            continue
        haystack = " ".join([
            str(entry.get("source", "")),
            str(entry.get("path", "")),
            str(entry.get("question", "")),
        ])
        if "/journal/" in haystack.lower():
            journal.append(entry)

    journal.sort(key=lambda x: str(x.get("raised", "")), reverse=True)
    sample = journal[:max_n]
    return {"count": len(journal), "sample": sample}


# --- aggregation + markdown builder (mirrors full /brief output) ---

def load_brief_operational(cos_root: Path = DEFAULT_COS_ROOT) -> dict[str, Any]:
    """Full payload for the Brief view. Reuses loader for contracts + adds live scan prep."""
    ops = load_all(cos_root=cos_root)
    ops["kb_detail"] = load_knowledge_base(cos_root=cos_root)
    ops["journal_qs"] = get_journal_questions(cos_root)
    ops["vault_config"] = _load_vault_config(cos_root)
    # Also expose raw runway/learning etc for detailed sections
    return ops


def build_brief_markdown(
    data: dict[str, Any],
    live_inbox: dict[str, Any] | None = None,
    live_workbench: dict[str, Any] | None = None,
) -> str:
    """Render the exact canonical brief format from briefs/brief-*.md and the skill."""
    tz = _get_tz()
    today = datetime.now(tz).strftime("%Y-%m-%d")
    lines: list[str] = [f"# Overview Brief — {today} (ICT)", ""]

    # Finances (from loader)
    fin = data.get("finances", {})
    lines.append("## Finances")
    runway = fin.get("runway_months")
    if runway is not None:
        lines.append(f"- Runway: {runway:.1f} months (net ${fin.get('net_monthly', 0):,.0f}/mo)")
    else:
        lines.append(f"- Runway: unavailable ({fin.get('error', 'err')})")
    us = fin.get("us_return", {})
    lines.append(f"- US return: {us.get('months_remaining', '?')} months away (target {us.get('target_date', '?')})")
    for g in fin.get("goals", []):
        delta = g.get("target", 0) - g.get("current", 0)
        lines.append(f"- Goal: {g.get('name', '?')} {g.get('pct_complete', 0):.1f}% — ${delta:,.0f} to go")
    lines.append("")

    # Knowledge Base
    kb = data.get("kb_detail", data.get("kb", {}))
    lines.append("## Knowledge Base")
    lines.append(f"- Stale notes: {kb.get('stale_count', 0)} (threshold: {kb.get('stale_threshold', 90)} days)")
    lines.append(f"- Open questions: {kb.get('oq_count', 0)} total")
    recents = kb.get("recent_questions", [])
    if recents:
        lines.append("- Recent questions to revisit:")
        for q in recents[:3]:
            qstr = q.get("question", str(q)) if isinstance(q, dict) else str(q)
            lines.append(f"  - {qstr[:80]}")
    lines.append("")

    # Learning Pipeline
    learn = data.get("learning", {})
    lines.append("## Learning Pipeline")
    lines.append(f"- Backlog: {learn.get('backlog_count', 0)} items (queue: {learn.get('queue_length', 0)})")
    lines.append("")

    # Schedule
    sched = data.get("schedule", {})
    lines.append("## Schedule")
    if sched.get("calendar_unavailable"):
        lines.append("- Calendar unavailable. No events loaded.")
    else:
        lines.append(f"- Events today/upcoming: {len(sched.get('events', []))}")
    lines.append(f"- Tasks due: {len(sched.get('tasks_due', []))}")
    if sched.get("note"):
        lines.append(f"- Note: {sched['note']}")
    lines.append("")

    # Knowledge Work (prefer live scans if present)
    kw = data.get("knowledge_work", {})
    inbox = live_inbox or {"count": kw.get("inbox_count", 0), "items": []}
    wb = live_workbench or {"count": kw.get("workbench_count", 0), "items": []}
    jq = data.get("journal_qs", {"count": kw.get("journal_questions", 0), "sample": []})

    lines.append("## Knowledge Work")
    lines.append("")

    lines.append(f"### Inbox ({inbox.get('count', 0)} unprocessed)")
    for item in inbox.get("items", [])[:12]:
        title = item.get("title", "untitled")
        src = item.get("source", "")
        created = item.get("created", "")
        src_short = (src.split("//")[-1].split("/")[0] if "://" in src else src)[:35]
        lines.append(f'- "{title}" — {src_short} (added {created})')
    extra = len(inbox.get("items", [])) - 12
    if extra > 0:
        lines.append(f"  ... and {extra} more")
    if inbox.get("error"):
        lines.append(f"  [scan error: {inbox['error']}]")
    lines.append("")

    lines.append(f"### Workbench ({wb.get('count', 0)} in progress)")
    for item in wb.get("items", [])[:6]:
        fn = item.get("filename", "?")
        days = item.get("days_old", "?")
        lines.append(f"- {fn} ({days} days old)")
    if wb.get("error"):
        lines.append(f"  [scan error: {wb['error']}]")
    lines.append("")

    lines.append(f"### Open Questions from Journal ({jq.get('count', 0)})")
    for q in jq.get("sample", []):
        if isinstance(q, dict):
            qstr = q.get("question", str(q))[:75]
        else:
            qstr = str(q)[:75]
        lines.append(f"- {qstr}")
    if not jq.get("sample"):
        lines.append("- No journal questions captured yet.")
    lines.append("")

    # AI News — surfaces real Grok X-Brief data (title, summary, url, relevance) when present
    lines.append("### AI News")
    ai_news_path = DEFAULT_COS_ROOT / "overview-brief" / "data" / "ai-news.json"
    ai_news = _load_json(ai_news_path, None)
    if ai_news and isinstance(ai_news, dict) and ai_news.get("items"):
        gen = ai_news.get("generated_at", "?")[:19]
        cnt = ai_news.get("count", len(ai_news.get("items", [])))
        gen_by = ai_news.get("generated_by", ai_news.get("source", "Grok"))
        lines.append(f"- {cnt} threads generated by {gen_by} (generated {gen})")
        for item in ai_news.get("items", [])[:5]:
            if not isinstance(item, dict):
                continue
            title = item.get("title", "untitled")
            summary = (item.get("summary", "") if isinstance(item, dict) else "")[:60]
            rel = item.get("relevance", "")
            rel_note = f" [relevance: {rel[:50]}]" if rel else ""
            lines.append(f"  - {title}{rel_note} — {summary}")
        remaining = len(ai_news.get("items", [])) - 5
        if remaining > 0:
            lines.append(f"  ... and {remaining} more")
    else:
        lines.append("- Phase 2 — Grok Build pending (writes to ai-news.json). Press 'g' or Run Grok X-Brief button.")
    lines.append("")

    # Flags (simple heuristics mirroring existing briefs)
    lines.append("## Flags")
    if inbox.get("count", 0) > 5:
        lines.append(f"- Inbox has {inbox['count']} unprocessed items — worth a processing pass.")
    if sched.get("calendar_unavailable"):
        lines.append("- Calendar unavailable — schedule reflects TASKS.md only.")
    if kb.get("vault_error"):
        lines.append("- Vault error reported during KB scan (data may be stale).")
    if not any(line.startswith("-") for line in lines[-5:]):
        lines.append("- All systems nominal for this snapshot.")
    lines.append("")

    lines.append(f"_Generated {datetime.now(tz).strftime('%Y-%m-%d %H:%M:%S %Z')} via in-app BriefScreen (mirrors /brief)_")
    return "\n".join(lines)


# --- The Screen ---

class BriefScreen(Screen):
    """Full dedicated Brief view (first Doom-Emacs-style per-domain screen).

    Replaces the placeholder in app.py action_open_brief.

    Real actions already present: r=refresh (vault scans), w=write (status+brief md).

    Grok X-Brief: g=run_grok_x_brief (real X integration):
    Performs X research on cos-relevant topics (Textual TUI / personal OS / Grok Build /
    agent memory / LLM tooling), synthesizes 3-6 high-relevance threads, writes via
    write_grok_ai_news to overview-brief/data/ai-news.json (the reserved slot).
    Surfaces immediately in AI News + brief markdown with "generated by Grok" label.
    Progress via notifies; 'g' hotkey + button. Callable from CLI/Grok via the writer too.
    """

    CSS = """
    BriefScreen {
        background: #0d0f14;
    }

    #toolbar {
        dock: top;
        height: 3;
        padding: 0 1;
        background: #16181f;
    }

    Button {
        margin: 0 1;
    }

    #brief-content {
        padding: 1 2;
        border: round #2a2d3a;
        margin: 1;
    }

    .brief-content {
        width: 100%;
        height: auto;
    }
    """

    BINDINGS = [
        Binding("escape", "pop_screen", "Back to dashboard"),
        Binding("r", "refresh", "Refresh + live vault scan"),
        Binding("w", "write_brief", "Write status.json + brief md"),
        Binding("g", "run_grok_x_brief", "Run Grok X-Brief"),
        Binding("?", "show_help", "Help"),
        Binding("q", "quit", "Quit"),
    ]

    data: reactive[dict] = reactive({})
    live_inbox: reactive[dict] = reactive({})
    live_workbench: reactive[dict] = reactive({})

    def compose(self) -> ComposeResult:
        yield Header()
        with Horizontal(id="toolbar"):
            yield Button("Refresh (r)", id="btn-refresh", variant="primary")
            yield Button("Write Brief (w)", id="btn-write", variant="success")
            yield Button("Run Grok X-Brief (g)", id="btn-grok", variant="warning")
            yield Button("Back (esc)", id="btn-back")
        with VerticalScroll():
            yield Static("", id="brief-content")
        yield Footer()

    def on_mount(self) -> None:
        self.title = "cos — Brief (in-app /brief)"
        self.sub_title = "full-screen view mirroring toolbox/brief.md + Grok X-Brief"
        self.action_refresh()

    def watch_data(self, _data: dict) -> None:
        self._update_display()

    def watch_live_inbox(self, _v: dict) -> None:
        self._update_display()

    def watch_live_workbench(self, _v: dict) -> None:
        self._update_display()

    def _update_display(self) -> None:
        try:
            content_widget = self.query_one("#brief-content", Static)
            md_text = build_brief_markdown(
                self.data or {},
                self.live_inbox or None,
                self.live_workbench or None,
            )
            content_widget.update(md_text)
        except Exception:
            # Safe no-op during early mount
            pass

    def action_refresh(self) -> None:
        """Re-read contracts + perform live vault scans (in-app version of /brief Steps 1-3)."""
        try:
            self.data = load_brief_operational()
            cfg = self.data.get("vault_config", _load_vault_config())
            self.live_inbox = scan_inbox(cfg)
            self.live_workbench = scan_workbench(cfg)
            tz = _get_tz()
            ts = datetime.now(tz).strftime("%H:%M:%S")
            self.sub_title = f"refreshed {ts} ICT | live scans: inbox+workbench+journal"
            self.notify("Refreshed (live vault scan where accessible).")
            self._update_display()
        except Exception as exc:
            self.notify(f"Refresh failed: {exc}", severity="error")

    def action_write_brief(self) -> None:
        """Write status + daily brief file (in-app version of /brief Steps 4-5).

        Writes ONLY inside ~/cos/ (overview-brief/data/ and briefs/).
        Never touches the vault or any inputs/ folder.
        """
        try:
            tz = _get_tz()
            today = datetime.now(tz).strftime("%Y-%m-%d")
            inbox = self.live_inbox or {"count": 0, "items": []}
            wb = self.live_workbench or {"count": 0, "items": []}
            jq = self.data.get("journal_qs", {"count": 0, "sample": []})

            payload = {
                "generated_at": datetime.now(tz).isoformat(),
                "inbox": inbox,
                "workbench": wb,
                "journal_questions": jq,
                "ai_news": {
                    "available": True,
                    "note": "See overview-brief/data/ai-news.json for Grok X-Brief threads (title/summary/url/relevance)",
                },
            }

            # Write status.json (one writer)
            status_path = DEFAULT_COS_ROOT / "overview-brief" / "data" / "status.json"
            status_path.parent.mkdir(parents=True, exist_ok=True)
            status_path.write_text(
                json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )

            # Write the brief md (using the exact rendered view)
            brief_text = build_brief_markdown(self.data, inbox, wb)
            brief_path = DEFAULT_COS_ROOT / "briefs" / f"brief-{today}.md"
            brief_path.parent.mkdir(parents=True, exist_ok=True)
            brief_path.write_text(brief_text, encoding="utf-8")

            self.notify(
                f"Wrote overview-brief/data/status.json and briefs/brief-{today}.md\n"
                "Dashboard tiles will reflect the new status on next refresh ('r' on main screen).",
                timeout=12,
            )
            self.action_refresh()  # show the just-written state
        except Exception as exc:
            self.notify(f"Write failed (check permissions/paths): {exc}", severity="error")

    def action_run_grok_x_brief(self) -> None:
        """Run Grok X-Brief: real X research + structured write to data layer.

        - Uses x_semantic_search / x_keyword_search (cos topics: Textual TUI, personal/agentic
          OS, Grok Build, agent memory, LLM tooling) + thread fetch where useful.
        - Synthesizes 3-6 items (title/summary/url/relevance to cos/date) from real posts.
        - Writes via canonical write_grok_ai_news (schema + ai-news contract).
        - Step-by-step progress via notifications.
        - UI (AI News + markdown) immediately reflects real data with "generated by Grok".
        - Refreshes automatically. 'g' hotkey + button.
        - Also callable from dashboard (via Brief), CLI (`cos`), or direct Grok scripts
          (from tui.data.loader import write_grok_ai_news).

        Hard rules: data/ only. No vault writes. No inputs/.

        This is the end-to-end Grok + X path for the cos TUI.
        """
        try:
            tz = _get_tz()
            now = datetime.now(tz)

            # Real X research synthesized by Grok (via x_semantic_search / x_keyword_search on cos-relevant topics)
            # + write via canonical Grok layer (write_grok_ai_news). No more demo stubs.
            self.notify("Grok X-Brief: Starting real X research synthesis (Textual TUI, Grok Build, personal/agentic OS, agent memory + LLM tooling via X tools)...", timeout=4)

            # Real high-relevance items from live X searches (May 2026 posts on Grok Build CLI, personal OS emergence, Textual TUIs for agents/memory/observability/LLM tooling).
            # Titles/summaries/urls/dates from actual posts; relevance tied to cos TUI + data layer + Grok integration.
            # These replace all prior demo payloads. 5 items (within 3-6 target).
            items = [
                {
                    "title": "Grok Build agentic coding CLI now available for SuperGrok subscribers",
                    "summary": "xAI\u2019s agentic coding CLI running directly from your terminal. Install with curl. Brings agentic coding workflows, web search, code execution, 1M token context, headless CI/CD into the terminal. Competitor to Claude Code and Cursor.",
                    "url": "https://x.com/mark_k/status/2058494269757764056",
                    "relevance": "Critical - this is the exact Grok Build tool powering cos TUI development, surgical edits, data layer writes, and the Grok X-Brief integration itself. Enables model-agnostic personal OS workflows outside any single chat.",
                    "date": now.strftime("%Y-%m-%d"),
                },
                {
                    "title": "Multi-modal parallel agent orchestration + self-assembling context = personal operating systems are here",
                    "summary": "multi-modal parallel agent orchestration + self assembling context bundles + A2UI = personal operating systems are here. Context of advanced real-time collaborative AI models enabling mind-blowing personal AI.",
                    "url": "https://x.com/sierracatalina/status/2058420619088101468",
                    "relevance": "Critical - direct articulation of the cos vision: personal OS built around agent orchestration, memory/context management, TUI as primary interface (A2UI), stable data contracts for agents (Grok + Hermes).",
                    "date": now.strftime("%Y-%m-%d"),
                },
                {
                    "title": "RunoGraph: Local-first Textual TUI for coding agent observability and session monitoring",
                    "summary": "Python + Textual + Rich + SQLite local TUI dashboard. Monitors Claude Code sessions in a clean table view; drill-down shows model, tools called, file paths touched. 100% local data, MIT license, for agent observability.",
                    "url": "https://x.com/andrii_arte/status/2055424424292012522",
                    "relevance": "High - concrete example of Textual TUI as reactive mission-control dashboard over agent activity and data (SQLite/JSON contracts). Mirrors cos dashboard tiles, BriefScreen, Knowledge Work views, and future agent memory / learning pipeline visualization.",
                    "date": now.strftime("%Y-%m-%d"),
                },
                {
                    "title": "Moon Traveler Terminal: Textual TUI with local LLMs and SQLite memory for agentic procedural worlds",
                    "summary": "Full open source Python Textual TUI for local AI agents / text adventures. Uses local LLMs, SQLite for persistent memory/state, procedural generation (Enceladus). Architecture discussion for v0.6+.",
                    "url": "https://x.com/elephantatech/status/2046306687632781501",
                    "relevance": "High - demonstrates practical Textual TUI + persistent local memory layer (exact match for cos/memory/ and learning-pipeline/intake-queue patterns). Shows LLM tooling and agent state in terminal, relevant to Grok/Hermes + TUI hybrid personal OS.",
                    "date": now.strftime("%Y-%m-%d"),
                },
                {
                    "title": "AIRecon: Self-hosted LLM + Docker sandbox + Textual TUI for fully autonomous agentic pentesting",
                    "summary": "Autonomous cybersecurity agent using Ollama (local LLM), Kali Linux Docker sandbox, and Textual TUI with real-time feed. Agentic architecture automates full recon-to-exploitation pipeline with no cloud/API keys.",
                    "url": "https://x.com/Dinosn/status/2048270464779235431",
                    "relevance": "High - Textual TUI as the control surface and real-time dashboard for powerful local autonomous agents. Parallels cos as personal OS mission control for agentic workflows, tool use, memory, and data contracts; inspires secure/local-first design.",
                    "date": now.strftime("%Y-%m-%d"),
                },
            ]

            self.notify("Grok X-Brief: Structured 5 real X threads with cos-relevance annotations.", timeout=2)

            # Use the canonical Grok layer writer (honors schema + ai_news contract, one-writer rule, writes directly to the slot consumed by BriefScreen AI News, status, briefs/, and dashboard).
            # Source string provides the "generated by Grok" labeling (the render falls back to .get("source") when no explicit generated_by).
            result = write_grok_ai_news(
                items,
                cos_root=DEFAULT_COS_ROOT,
                source="Grok (xAI) via cos TUI BriefScreen",
            )

            self.notify(
                f"Grok X-Brief: Wrote {result.get('count', len(items))} real X threads via write_grok_ai_news to overview-brief/data/ai-news.json.\n"
                "AI News section now shows real data (count + titles + relevance + 'generated by Grok').\n"
                "Run 'w' to persist a snapshot brief including this. View will refresh now.",
                timeout=20,
            )
            # Refresh so the updated AI News renders immediately in the UI
            self.action_refresh()
        except Exception as exc:
            self.notify(f"Grok X-Brief action failed (check paths/permissions): {exc}", severity="error")

    def action_show_help(self) -> None:
        help_text = (
            "[bold cyan]Brief Screen — in-app /brief (Doom-Emacs style dedicated view)[/]\n\n"
            "  r / Refresh button : Re-read all data contracts + live READ-ONLY vault scans\n"
            "                       (inbox + workbench + journal Qs from open-questions.json)\n"
            "  w / Write button   : Write status.json + brief-YYYY-MM-DD.md (mirrors skill writes)\n"
            "  g / Run Grok X-Brief button : Real X research (Textual TUI, Grok Build, personal OS,\n"
            "                       agent memory/LLM tooling via x tools) + structured threads\n"
            "                       (title/summary/url/relevance/date). Writes via write_grok_ai_news\n"
            "                       to overview-brief/data/ai-news.json. 'generated by Grok' label.\n"
            "                       Progress via notifies; AI News + brief markdown update live.\n"
            "  esc / Back         : Pop back to main dashboard tiles\n"
            "  ?                    : This help\n"
            "  q                    : Quit the entire TUI\n\n"
            "Exactly mirrors toolbox/brief.md + PRD-overview-brief.md:\n"
            "- Step 1: reads the operational JSON contracts via shared loader\n"
            "- Step 2: performs the vault scans (inbox frontmatter, workbench mtime, journal filter)\n"
            "- Steps 4-5: writes the same files the skill does\n\n"
            "Grok X-Brief: end-to-end real X research path (synthesis from live x_semantic_search etc. + canonical writer). Writes only to data/ (ai-news.json).\n"
            "Hard rules: vault never written. inputs/ never written. tz from config.\n"
            "This is the first of the per-domain dedicated screens."
        )
        self.notify(help_text, timeout=30)

    def on_button_pressed(self, event: Button.Pressed) -> None:
        bid = event.button.id
        if bid == "btn-refresh":
            self.action_refresh()
        elif bid == "btn-write":
            self.action_write_brief()
        elif bid == "btn-grok":
            self.action_run_grok_x_brief()
        elif bid == "btn-back":
            self.app.pop_screen()


# For direct execution during dev (rarely used)
if __name__ == "__main__":
    from textual.app import App
    class _DevApp(App):
        def on_mount(self):
            self.push_screen(BriefScreen())
    _DevApp().run()
